### ISSUE TITLE
error occured in the test phase

### ISSUE THREAD

**Issue by gk616828144** [unsky/FPN#23]
Hello, sir. I met an error in the test phase like this:
"
Traceback (most recent call last):
  File "./tools/test_net.py", line 90, in <module>
    test_net(net, imdb, max_per_image=args.max_per_image, vis=args.vis)
  File "/home/gaokun/FPN-caffe/tools/../lib/fast_rcnn/test.py", line 268, in test_net
    scores, boxes = im_detect(net, im, box_proposals)
  File "/home/gaokun/FPN-caffe/tools/../lib/fast_rcnn/test.py", line 183, in im_detect
    pred_boxes = bbox_transform_inv(boxes, box_deltas)
  File "/home/gaokun/FPN-caffe/tools/../lib/fast_rcnn/bbox_transform.py", line 47, in bbox_transform_inv
    pred_ctr_x = dx * widths[:, np.newaxis] + ctr_x[:, np.newaxis]
ValueError: operands could not be broadcast together with shapes (225,2) (300,1)
"
I don't know how to solve it. can you give me some advice ?

Thank you!

**Comment by unsky** [comment]
@gk616828144  i think you should use my new codes.
