### ISSUE TITLE
training problem 

### ISSUE THREAD

**Issue by jjy201314** [unsky/FPN#32]
when i  training ,i have a problem :

Traceback (most recent call last):
  File "/home/hncs/liuwei/FPN1/tools/../lib/rpn/proposal_layer.py", line 14, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "/home/hncs/liuwei/FPN1/tools/../lib/fast_rcnn/nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms
Traceback (most recent call last):
  File "./tools/train_net.py", line 113, in <module>
    max_iters=args.max_iters)
  File "/home/hncs/liuwei/FPN1/tools/../lib/fast_rcnn/train.py", line 143, in train_net
    pretrained_model=pretrained_model)
  File "/home/hncs/liuwei/FPN1/tools/../lib/fast_rcnn/train.py", line 46, in __init__
    self.solver = caffe.SGDSolver(solver_prototxt)
SystemError: NULL result without error in PyObject_Call

But  i running on the GPU,and the id is right,  i   don't  know  what's wrong.
thank  you  very   much!
@unsky

**Comment by xubo00** [comment]
可以尝试在lib目录下重新make,之前我遇到过no module named cpu_nms,就是这样解决的,另外需要看一下Makefile.config里面的内容,不知道你是在cpu还是gpu下跑的算法.
