### ISSUE TITLE
FPN训练小目标数据

### ISSUE THREAD

**Issue by hmjbuaa** [unsky/FPN#37]
你好，unsky。我在做小目标检测的实验，之前用你的旧代码（VGG16模型）召回率可以达到90%左右，用新的代码（RESNET50 sharedrcnn）召回率只有70%左右。尝试改了scales为[4,8]和FPN/lib/fast_rcnn/config.py里的一些参数，但是效果都不理想，能不能给一些建议，谢谢！

**Comment by unsky** [comment]
fpn非常适合的情况是大小目标在同一图片中，如果单纯只有小目标可以去掉一些fpn的高层。

**Comment by hmjbuaa** [comment]
@unsky 好的，谢谢

**Comment by wolf345** [comment]
Set proposal method: selective_search
Appending horizontally-flipped training examples...
wrote gt roidb to /home/wolf/Desktop/FPN-master/data/cache/voc_2007_trainval_gt_roidb.pkl
Traceback (most recent call last):
  File "./tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 66, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/wolf/Desktop/FPN-master/tools/../lib/fast_rcnn/train.py", line 103, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/wolf/Desktop/FPN-master/tools/../lib/datasets/imdb.py", line 106, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/home/wolf/Desktop/FPN-master/tools/../lib/datasets/imdb.py", line 67, in roidb
    self._roidb = self.roidb_handler()
  File "/home/wolf/Desktop/FPN-master/tools/../lib/datasets/pascal_voc.py", line 128, in selective_search_roidb
    ss_roidb = self._load_selective_search_roidb(gt_roidb)
  File "/home/wolf/Desktop/FPN-master/tools/../lib/datasets/pascal_voc.py", line 162, in _load_selective_search_roidb
    'Selective search data not found at: {}'.format(filename)
AssertionError: Selective search data not found at: /home/wolf/Desktop/FPN-master/data/selective_search_data/voc_2007_trainval.mat
@hmjbuaa @unsky 出现这个问题是什么原因呢？我用的自己的数据集，而且把cache里面的清楚了

**Comment by unsky** [comment]
这个问题是无法读取yml导致的，因该是读取yml的库不兼容导致的，

**Comment by wolf345** [comment]
@hmjbuaa @unsky 旧代码哪里能下载，需要尝试一下vgg16版本的，谢谢啦

**Comment by wolf345** [comment]
Writing drone VOC results file
VOC07 metric? Yes
AP for drone = 0.0000
Mean AP = 0.0000
~~~~~~~~
Results:
0.000
0.000
~~~~~~~~
@unsky @hmjbuaa   我训练自己的数据，出现这个问题是什么原因导致的呢？

**Comment by chaobeiying** [comment]
@wolf345  ap值为0是什么原因你找到了吗？

**Comment by mantou22** [comment]
您好，请问为什么我训练自己的模型会怎么慢速度？
前面几百次迭代，每20次只需要 34S 左右， 到了2000次左右时， 每20次需要 5-6分钟 为什么会那么慢？？？？？  我的显卡是 GPU 1080Ti 的  12G运行内存

**Comment by mantou22** [comment]
> 你好，unsky。我在做小目标检测的实验，之前用你的旧代码（VGG16模型）召回率可以达到90%左右，用新的代码（RESNET50 sharedrcnn）召回率只有70%左右。尝试改了scales为[4,8]和FPN/lib/fast_rcnn/config.py里的一些参数，但是效果都不理想，能不能给一些建议，谢谢！
您好，我也是做小目标检测，您好，请问为什么我训练自己的模型会怎么慢速度？
前面几百次迭代，每20次只需要 34S 左右， 到了2000次左右时， 每20次需要 5-6分钟 为什么会那么慢？？？？？  我的显卡是 GPU 1080Ti 的  12G运行内存
