### ISSUE TITLE
when I run the demo.py,there is a problem,could you help me ?

### ISSUE THREAD

**Issue by sujinpeng** [unsky/FPN#61]
Loaded network /media/E/FPN/data/pretrained_model/fpn_iter_40000.caffemodel
Traceback (most recent call last):
  File "./demo2.py", line 139, in <module>
    _, _= im_detect(net, im)
  File "/media/E/FPN/tools/../lib/fast_rcnn/test.py", line 298, in im_detect
    box_deltas = box_deltas * stds + means
ValueError: operands could not be broadcast together with shapes (1000,36) (84,)

**Comment by leonshek** [comment]
modify test.prototxt
change num_output

**Comment by SineXue** [comment]
im_detect(net, im)还有一个参数是num_classes，需要指明你修改的类别数，要不会按照默认的21类，另外还有prototxt文件里面的修改正确了没

**Comment by mantou22** [comment]
Loaded network /home/xmpu234/Documents/FPN-caffe_1/data/faster_rcnn_models/fpn_iter_25000.caffemodel
Traceback (most recent call last):
  File "/home/xmpu234/Documents/FPN-caffe_1/tools/demo.py", line 142, in <module>
    _, _= im_detect(net, im)
  File "/home/xmpu234/Documents/FPN-caffe_1/tools/../lib/fast_rcnn/test.py", line 158, in im_detect
    rois2 = net.blobs['rpn_rois/p2'].data.copy()
KeyError: 'rpn_rois/p2'



 when I run the demo.py,there is a problem,could you help me??

**Comment by mantou22** [comment]
@sujinpeng 你好，请问你解决了你的问题吗？ 具体需要改那几个参数呀？  我训练的是2类的，test.prototxt将21--->改为2 ， 将 84改为 8 。  还有其他地方需要改吗？

**Comment by mantou22** [comment]
您好，请问为什么我训练自己的模型会怎么慢速度？
前面几百次迭代，每20次只需要 34S 左右， 到了2000次左右时， 每20次需要 5-6分钟 为什么会那么慢？？？？？  我的显卡是 GPU 1080Ti 的  12G运行内存
