### ISSUE TITLE
another problem

### ISSUE THREAD

**Issue by sujinpeng** [unsky/FPN#63]
Traceback (most recent call last):
File "./tools/train_net.py", line 112, in
max_iters=args.max_iters)
File "/media/E/FPN-caffe4/tools/../lib/fast_rcnn/train.py", line 160, in train_net
model_paths = sw.train_model(max_iters)
File "/media/E/FPN-caffe4/tools/../lib/fast_rcnn/train.py", line 101, in train_model
self.solver.step(1)
File "/media/E/FPN-caffe4/tools/../lib/rpn/anchor_target_layer.py", line 132, in forward
if int(item)==p:
ValueError: cannot convert float NaN to integer

**Comment by unsky** [comment]
numpy version is too low

**Comment by sujinpeng** [comment]
thanyou very much !! 
I habe a question,in your code 
             k = np.floor(k0 + np.log2(np.sqrt(areas)*1.0 / 64)) 
could you tell me why is the 64? in the paper ,it's 224

**Comment by sujinpeng** [comment]
Thank you very much. Then,I found the result of the cfg.TEST.BBOX_REG=False is better than the  cfg.TEST.BBOX_REG=True, why?

**Comment by mantou22** [comment]
when I run the demo.py,there is a problem,could you help me??????

Loaded network /home/xmpu234/Documents/FPN-caffe_1/data/faster_rcnn_models/fpn_iter_25000.caffemodel
Traceback (most recent call last):
File "/home/xmpu234/Documents/FPN-caffe_1/tools/demo.py", line 142, in
_, _= im_detect(net, im)
File "/home/xmpu234/Documents/FPN-caffe_1/tools/../lib/fast_rcnn/test.py", line 158, in im_detect
rois2 = net.blobs['rpn_rois/p2'].data.copy()
KeyError: 'rpn_rois/p2

**Comment by mantou22** [comment]
您好，请问为什么我训练自己的模型会怎么慢速度？
前面几百次迭代，每20次只需要 34S 左右， 到了2000次左右时， 每20次需要 5-6分钟 为什么会那么慢？？？？？  我的显卡是 GPU 1080Ti 的  12G运行内存
