### ISSUE TITLE
输入层python_layer的具体实现?

### ISSUE THREAD

**Issue by shuishiwojiade** [unsky/FPN#65]
你好，想知道输入层python_layer的具体实现，但是没找到该层。

**Comment by unsky** [comment]
image_stride 的倍数

**Comment by mantou22** [comment]
when I run the demo.py,there is a problem,could you help me??????

Loaded network /home/xmpu234/Documents/FPN-caffe_1/data/faster_rcnn_models/fpn_iter_25000.caffemodel
Traceback (most recent call last):
File "/home/xmpu234/Documents/FPN-caffe_1/tools/demo.py", line 142, in
_, _= im_detect(net, im)
File "/home/xmpu234/Documents/FPN-caffe_1/tools/../lib/fast_rcnn/test.py", line 158, in im_detect
rois2 = net.blobs['rpn_rois/p2'].data.copy()
KeyError: 'rpn_rois/p2
