### ISSUE TITLE
如果想要使用hard negative mining应该如何修改？

### ISSUE THREAD

**Issue by leonshek** [unsky/FPN#67]
@unsky hard negative mining的实现有吗？

**Comment by mantou22** [comment]
when I run the demo.py,there is a problem,could you help me??????

Loaded network /home/xmpu234/Documents/FPN-caffe_1/data/faster_rcnn_models/fpn_iter_25000.caffemodel
Traceback (most recent call last):
File "/home/xmpu234/Documents/FPN-caffe_1/tools/demo.py", line 142, in
_, _= im_detect(net, im)
File "/home/xmpu234/Documents/FPN-caffe_1/tools/../lib/fast_rcnn/test.py", line 158, in im_detect
rois2 = net.blobs['rpn_rois/p2'].data.copy()
KeyError: 'rpn_rois/p2

**Comment by leonshek** [comment]
> when I run the demo.py,there is a problem,could you help me??????
> 
> Loaded network /home/xmpu234/Documents/FPN-caffe_1/data/faster_rcnn_models/fpn_iter_25000.caffemodel
> Traceback (most recent call last):
> File "/home/xmpu234/Documents/FPN-caffe_1/tools/demo.py", line 142, in
> _, _= im_detect(net, im)
> File "/home/xmpu234/Documents/FPN-caffe_1/tools/../lib/fast_rcnn/test.py", line 158, in im_detect
> rois2 = net.blobs['rpn_rois/p2'].data.copy()
> KeyError: 'rpn_rois/p2

@mantou22 
修改lib/rpn/proposal_layer.py
将layer_params = yaml.load(self.param_str_)修改为
try:layer_params = yaml.load(self.param_str_)
except:layer_params = yaml.load(self.param_str)
修改lib/rpn/as_rois.py
将layer_params = yaml.load(self.param_str_)修改为
try:layer_params = yaml.load(self.param_str_)
except:layer_params = yaml.load(self.param_str)
编译lib：
cd lib
rm 所有的so文件，重新build，make
